// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: logproto/logproto.proto

package logproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*Stream              `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_logproto_logproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetStreams() []*Stream {
	if x != nil {
		return x.Streams
	}
	return nil
}

type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        string                 `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_logproto_logproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{1}
}

func (x *Stream) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *Stream) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_logproto_logproto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{2}
}

func (x *Entry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Entry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_logproto_logproto_proto protoreflect.FileDescriptor

const file_logproto_logproto_proto_rawDesc = "" +
	"\n" +
	"\x17logproto/logproto.proto\x12\blogproto\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\vPushRequest\x12*\n" +
	"\astreams\x18\x01 \x03(\v2\x10.logproto.StreamR\astreams\"K\n" +
	"\x06Stream\x12\x16\n" +
	"\x06labels\x18\x01 \x01(\tR\x06labels\x12)\n" +
	"\aentries\x18\x02 \x03(\v2\x0f.logproto.EntryR\aentries\"U\n" +
	"\x05Entry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04lineB&Z$github.com/habakke/promtail/logprotob\x06proto3"

var (
	file_logproto_logproto_proto_rawDescOnce sync.Once
	file_logproto_logproto_proto_rawDescData []byte
)

func file_logproto_logproto_proto_rawDescGZIP() []byte {
	file_logproto_logproto_proto_rawDescOnce.Do(func() {
		file_logproto_logproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logproto_logproto_proto_rawDesc), len(file_logproto_logproto_proto_rawDesc)))
	})
	return file_logproto_logproto_proto_rawDescData
}

var file_logproto_logproto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_logproto_logproto_proto_goTypes = []any{
	(*PushRequest)(nil),           // 0: logproto.PushRequest
	(*Stream)(nil),                // 1: logproto.Stream
	(*Entry)(nil),                 // 2: logproto.Entry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_logproto_logproto_proto_depIdxs = []int32{
	1, // 0: logproto.PushRequest.streams:type_name -> logproto.Stream
	2, // 1: logproto.Stream.entries:type_name -> logproto.Entry
	3, // 2: logproto.Entry.timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_logproto_logproto_proto_init() }
func file_logproto_logproto_proto_init() {
	if File_logproto_logproto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logproto_logproto_proto_rawDesc), len(file_logproto_logproto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logproto_logproto_proto_goTypes,
		DependencyIndexes: file_logproto_logproto_proto_depIdxs,
		MessageInfos:      file_logproto_logproto_proto_msgTypes,
	}.Build()
	File_logproto_logproto_proto = out.File
	file_logproto_logproto_proto_goTypes = nil
	file_logproto_logproto_proto_depIdxs = nil
}
